require('dotenv').config();
const nodemailer = require('nodemailer');

exports.handler = async (event, context) => {
    console.log('Event received:', event);

    if (event.httpMethod !== 'POST') {
        return {
            statusCode: 405,
            body: JSON.stringify({ error: 'Method not allowed' }),
        };
    }

    let data;
    try {
        if (event.headers['content-type'] === 'application/json') {
            data = JSON.parse(event.body);
        } else {
            const params = new URLSearchParams(event.body);
            data = Object.fromEntries(params);
        }
    } catch (error) {
        console.error('Error parsing input data:', error);
        return {
            statusCode: 400,
            body: JSON.stringify({ error: 'Invalid input data' }),
        };
    }

    const { firstName, lastName, email, budget, timeframe, message } = data;

    console.log('Parsed form data:', { firstName, lastName, email, budget, timeframe, message });

    let transporter = nodemailer.createTransport({
        service: 'Gmail',
        auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASS,
        },
    });

    let mailOptions = {
        from: process.env.EMAIL_USER,
        to: 'duder@dudeworth.com',
        subject: 'New Contact Form Submission: We’ve Got Data!',
        text: `Greetings, Human Operators of DudeWorth,

An intelligent entity (a potential client) has interfaced with our system and submitted a new contact form. Here are the deets:

---

**First Name:** ${firstName}

**Last Name:** ${lastName}

**Email:** ${email}

**Budget:** ${budget}

**Time Frame:** ${timeframe}

**Message:**
${message}

---

This data packet needs your human touch. Engage with the sender at your earliest convenience to optimize their experience.

Best regards,
Your Friendly AI at DudeWorth

---

**Note:** This message was generated by our infallible AI. Please do not reply directly to this email.`,
    };

    try {
        console.log('Attempting to send email...');
        await transporter.sendMail(mailOptions);
        console.log('Email sent successfully');
        
        return {
            statusCode: 200,
            headers: {
                'Content-Type': 'text/html; charset=UTF-8',
            },
            body: `<html><body>
                   <p>Thank you, human! Your message has been successfully sent through our neural networks. We’ll reply soon!</p>
                   <script>
                     setTimeout(function() {
                       window.location.href = 'https://dudeworth.com/index.html';
                     }, 5000);
                   </script>
                   </body></html>`,
        };
    } catch (error) {
        console.error('Error sending email:', error);
        return {
            statusCode: 500,
            headers: {
                'Content-Type': 'text/html; charset=UTF-8',
            },
            body: `<html><body>
                   <p>Oops! Our circuits got tangled. Please try sending your message again.</p>
                   <script>
                     setTimeout(function() {
                       window.location.href = 'https://dudeworth.com';
                     }, 5000);
                   </script>
                   </body></html>`,
        };
    }
};

